name: Deploy Franklin.jl site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'

      - name: Install Franklin.jl
        run: julia -e 'using Pkg; Pkg.add("Franklin")'

      - name: Build site
        run: julia -e 'using Franklin; optimize()'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./__site
          keep_files: false
